### ISSUE TITLE
Missing deps?

### ISSUE THREAD

**Issue by Diegovsky** [GabrielMCPinto/autoclicker-py#1]
Hello, I tried to run this on Arch Linux with python 3.10 and it seems that there are dependencies missing.
Output of `uname -a`:
```
Linux ryzenarch 5.18.5-zen1-1-zen #1 ZEN SMP PREEMPT_DYNAMIC Thu, 16 Jun 2022 20:40:47 +0000 x86_64 GNU/Linux
```
![image](https://user-images.githubusercontent.com/46163903/175840198-a71a8ea9-3b61-4082-a9b4-83d02146f0ed.png)

Could you clarify which dependencies it needs?

**Comment by GabrielMCPinto** [comment]
Fixed in 0f2eb8e
